# Generated by Django 3.2 on 2021-05-05 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='story_date',
            field=models.DateField(null=True, verbose_name=datetime.datetime(2021, 5, 6, 0, 37, 51, 768943)),
        ),
    ]
