# Generated by Django 3.2 on 2021-05-05 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0002_userstory_story_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='story_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 6, 3, 13, 19, 878286), null=True),
        ),
    ]
