# Generated by Django 3.2 on 2021-05-09 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0004_auto_20210509_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstory',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='userstory',
            name='story_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 9, 16, 26, 31, 622387), null=True),
        ),
    ]
